# Generated by Django 4.2.5 on 2023-11-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
